workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: "3.24.0"
      xcode: latest
      cocoapods: default
      java: "17"
    scripts:
      - name: Configure Firebase (iOS)
        script: |
          echo "$GOOGLE_SERVICE_INFO_PLIST" > ios/Runner/GoogleService-Info.plist
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Set iOS deployment target
        script: |
          cd ios
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/' Podfile
          cd ..
      - name: Install iOS pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa