workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: 3.29.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Set iOS deployment target
        script: |
          cd ios
          sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = 13.0/IPHONEOS_DEPLOYMENT_TARGET = 15.0/" Podfile
          sed -i '' "s/platform :ios, '13.0'/platform :ios, '15.0'/" Podfile
          cd ..
      - name: Install iOS pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa