platform :ios, '15.0'

flutter_application_path = File.expand_path('../..', __FILE__)
eval(File.read(File.join(flutter_application_path, '.dart_tool', 'flutter_export_environment.sh'))) unless File.exist?(File.join(flutter_application_path, '.dart_tool', 'flutter_export_environment.sh'))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end